import type { Metadata } from "next";
import { Geist, Geist_Mono, Jersey_10, Lexend, Source_Code_Pro } from "next/font/google";
import "./globals.css";

const jersey = Jersey_10({
  subsets: ['latin'],
  variable: '--font-jersey',
  weight: '400',
  display: 'swap',
});

const sourceCode = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--font-source-code-pro',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
  display: 'swap',
})

const lexend = Lexend({
  subsets: ['latin'],
  variable: '--font-lexend',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Deniel Ivor - Full-Stack Developer",
  description: "Generated by Deniel Ivor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${jersey.variable} ${geistSans.variable} ${geistMono.variable} ${sourceCode.variable} ${lexend.variable} antialiased bg-background"`}
      >
       
        <div className="w-full max-w-[1440px] mx-auto px-2">
          {children}
        </div>
       
      </body>
    </html>
  );
}
